# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  # - name: ConveRTTokenizer
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  # - name: ConveRTFeaturizer
  - name: DIETClassifier
    epochs: 10
  - name: EntitySynonymMapper
  - name: "ResponseSelector"
    retrieval_intent: chitchat
    epochs: 10
  - name: "ResponseSelector"
    retrieval_intent: out_of_scope
    epochs: 10
  - name: "ResponseSelector"
    retrieval_intent: COVID
    epochs: 10

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
